services:
  - type: web
    name: spring-back
    env: docker
    dockerfilePath: ./dockerfile
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false