# src\main\resources\application.yml
server:
  port: 8090

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:MCvBIKwPaVjhmKBwFUdHDXzvfWeAZgaJ8XJr6cBsvNkPI9UvAWw7GzFMV6ZhHsI}
      expiration: 86400000 # 1 día
      refresh-token:
        expiration: 604800000 # 7 días

spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.spatial:
        enabled: true
    show-sql: true
  logging:
    level:
      com.healink.integrador: DEBUG