# src\main\resources\application.yml
server:
  port: 8090

application:
  security:
    jwt:
      llave-secreta: ${JWT_SECRET:MCvBIKwPaVjhmKBwFUdHDXzvfWeAZgaJ8XJr6cBsvNkPI9UvAWw7GzFMV6ZhHsI}
      expiracion: 86400 # 24 horas en segundos (no milisegundos)
      token-refresco:
        expiration: 604800 # 7 días en segundos

spring:
  # main:
    # allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.spatial:
        enabled: true
    show-sql: true
  logging:
    level:
      root: INFO
      org.springframework: DEBUG
      org.springframework.web: INFO
      org.springframework.security: DEBUG
      org.hibernate: INFO
      com.healink.integrador: DEBUG